FROM ubuntu:22.04.3

RUN apt update
RUN apt install python3 python3-pip -y

RUN pip3 install --upgrade pip
RUN pip3 install numpy
RUN pip3 install opencv-python
RUN pip3 install flask
RUN pip3 install pathlib
RUN pip3 install torch
RUN pip3 install torchvision
RUN pip3 install pyyaml

WORKDIR /parking_lot

COPY .  .

ENV FLASK_APP=app
CMD ["flask", "run"]