FROM python:3.9.13-slim-buster

RUN pip3 install --upgrade pip
RUN pip3 install numpy
RUN pip3 install opencv-python
RUN pip3 install flask
RUN pip3 install pathlib
RUN pip3 install torch
RUN pip3 install torchvision
RUN pip3 install pyyaml

WORKDIR /parking_lot

COPY .  .

ENV FLASK_APP=app
CMD ["flask", "run"]